language: go
arch:
    - amd64
    - arm64
go:
    - "1.14.x"
    - "1.13.x"
    - "1.12.x"
    - "1.11.x"
    - tip

before_install:
    - mkdir -p /home/travis/gopath-tmp
    - export GOPATH="/home/travis/gopath-tmp"

script:
    - make all coveralls
    
jobs:
    exclude:
        - os: linux
          arch: arm64
          go: 1.11.x
